# Generated by Django 3.1.5 on 2021-01-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20210130_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.IntegerField(auto_created=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
